apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: workshop-apps
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/stevenwadeconsulting/gitops-fundamentals-lab
  ref:
    branch: main
  secretRef:
    name: github-credentials
