name: docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docs/**
      - mkdocs.yml

permissions:
  contents: read

concurrency:
  group: "docs"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.x

      - name: setup cache
        run: |
          echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: handle cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: install mkdocs material
        run: |
          pip install mkdocs-material==9.7.6

      - name: build mkdocs
        run: |
          mkdocs build

      - name: upload to R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
          AWS_ENDPOINT_URL: https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
        run: |
          aws s3 sync public/ s3://workshop-platformfix-com/gitops/ --size-only
